apiVersion: apps/v1
kind: Deployment
metadata:
  name: john-redis
  namespace: grupp1
  labels:
    app: john-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: john-redis
  template:
    metadata:
      labels:
        app: john-redis
    spec:
      containers:
        - name: john-redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: john-guestbook-common-secrets
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: john-redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: john-redis-data
          persistentVolumeClaim:
            claimName: john-redis-data
