apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: john-frontend
spec:
  to:
    kind: Service
    name: john-frontend
  port:
    targetPort: 8080
  tls:
    termination: Edge
    insecureEdgeTerminationPolicy: Redirect
